language: node_js
node_js:
- '6'
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success: yarn run coverage
env:
  global:
    secure: EAoLGjfW/up7dKfI799Q390xcVosrh16ek2T6CgRQbuntyrtKkPwTQrV52FRiIOJ5w8Ta5Zbgqy27QS0kZ3yjltq2eWabWfCXqY1GyccdkBVqwmStU5eUA9nUjL6VGwKRbTOdmIbdK/4yv3oD7Ps043COOxhQ7WJjOSnofYzsWXe5nhoaEkkolAk0P4QmsMpdifUqJiD9Z+Uun248/PSALGgZBP+Og3yKRJTYmgLdOiEd9kU+eJ+CFcLsQ7SsDEqTNFuLSTjXAXV3VO2nfvxRyE/Erl+adDU+64Obw0DiVsmI+O9b4fAZhcc61fYWc35Qngam2cRbLJ8CAV9gS1E7EE+L1ZlUFBGN6cFPQxqQOJKf1MFv/NKSZ+LUhRLPWvZEzZYe/k8T4dXPCZnD+BhnKLg5uThRknn3Xg7bYH9Pv0suEzxAJSv7GuQnm8l0I4cINqsoS0XmEWQUZ1l3EulQTTNay9wUudryxOAUfUqSsIyAUkcce18Y+SJzzRvWpreqOP/RYxotqrqY9mjy8bbxS14l+Vk8m6pdJwivMqw0SKoxIdJOuygg+/wNLQ2j3x2KJwj/VzZVunxf4Va7xLbobgYB+EW6EKiWtZLLkFTnAmgG4MNjqzWTpJWpwC6CzeGD7c6XeXpvsjfg8+7zHpHWE2jkqHLLwzTpKMTV30cqKE=
