language: node_js
node_js:
- '8'
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success: yarn run coverage
env:
  global:
    secure: EAoLGjfW/up7dKfI799Q390xcVosrh16ek2T6CgRQbuntyrtKkPwTQrV52FRiIOJ5w8Ta5Zbgqy27QS0kZ3yjltq2eWabWfCXqY1GyccdkBVqwmStU5eUA9nUjL6VGwKRbTOdmIbdK/4yv3oD7Ps043COOxhQ7WJjOSnofYzsWXe5nhoaEkkolAk0P4QmsMpdifUqJiD9Z+Uun248/PSALGgZBP+Og3yKRJTYmgLdOiEd9kU+eJ+CFcLsQ7SsDEqTNFuLSTjXAXV3VO2nfvxRyE/Erl+adDU+64Obw0DiVsmI+O9b4fAZhcc61fYWc35Qngam2cRbLJ8CAV9gS1E7EE+L1ZlUFBGN6cFPQxqQOJKf1MFv/NKSZ+LUhRLPWvZEzZYe/k8T4dXPCZnD+BhnKLg5uThRknn3Xg7bYH9Pv0suEzxAJSv7GuQnm8l0I4cINqsoS0XmEWQUZ1l3EulQTTNay9wUudryxOAUfUqSsIyAUkcce18Y+SJzzRvWpreqOP/RYxotqrqY9mjy8bbxS14l+Vk8m6pdJwivMqw0SKoxIdJOuygg+/wNLQ2j3x2KJwj/VzZVunxf4Va7xLbobgYB+EW6EKiWtZLLkFTnAmgG4MNjqzWTpJWpwC6CzeGD7c6XeXpvsjfg8+7zHpHWE2jkqHLLwzTpKMTV30cqKE=
notifications:
  slack:
    secure: aHIGPJ4SiLqhoqyhGlvjjRGQtsM3S71za7SRvcM8L5Dede5topaoi/VHS2opyLjc4xvk/9cfgFtGsjefU19JgNSaKzYjs2QYSILWbiYszQUxc3917REEHzLJ1/XXhbFstOquOaQzFBD34/XdV3tqhCXJYonZewFOb8WEdFKZgs3pin+VqDPMrez6rAcnrEzuHDpPEEVGkPOXNdrEsuat/6Z+9RNDxKz5lu8qJNfJRg4tHxSm3kt54Qi569Pkg9CMNRwS5i6laNrv0q0mo+/opjZknpclBrW/i5j1SCepoywfn5lbSY8TU5h2ptwZU2yUKPaTOxaI5t6Bn0OUPBGBavbdyhEBKd5gMLDn8XIZln8LPzdp1Saab7z5knGkGkr298sz6QVqLvOUMVQsaSzpdACKD1jhxd1WDRZuzuyuFN0K1FGtaG8oTMUaisxtxvZH8iNCC09noLNCP9RodC4WNUJXEbL2ykzlweMaf6uhGTpYVEd3mjdd5o3wQMVnk1FwjK3Kq9ZK814VY6S3m+8fju7i12f3TnXT+4T4ZFy9VjnssgdJctFT7TJmUrP7ldDq1hWCsgsEcTJQhLRPiQt1QUqFcv5m2aRLWoFuMzlRcLpYSTrf2Ik1AClfQY2pi7NYGHrRsMIRwRO6Fii6eANvq1ZxUiyZtwc+fcesm8fDgsM=
